# Jekyll Configuration

# Site settings
title: norden.social
logo: "https://norden.social/system/accounts/avatars/000/008/749/original/b02c08b9ea5ef104.jpeg"
locale: de_DE
email: moin@norden.social
description: >-
  Finanzielles, Statusupdates und andere Informationen rund um norden.social
github_username: norden-social
repository: "norden-social/website"

author:
  name: norden.social
  email: moin@norden.social

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.26.2
show_excerpts: true  # Show excerpts on the homepage
minimal_mistakes_skin: "dirt"  # Skin options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Defaults for _posts and _pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: false
      comments: false
      share: false
      related: false

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Social media settings
social:
  type: Organisation
  name: norden.social e.V.
  links:
    - "https://blog.norden.social"
    - "https://norden.social"
    - "https://norden.social/@leuchtturm"
    - "https://github.com/norden-social"

# Footer settings
footer:
  links:
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://norden.social/@leuchtturm"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/norden-social"

# Open Graph image
og_image: https://norden.social/system/site_uploads/files/000/000/007/@2x/ae17b5a591dba4e8.png

# HTML compression settings
compress_html:
  clippings: all
  ignore:
    envs: development  # Disable compression in dev environment

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-octicons

# Sass/SCSS settings
sass:
  sass_dir: assets/css
  style: compressed

# Include specific files for processing
include:
  - "_pages"

# Exclude from processing (if needed)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/