---
remote_theme: mmistakes/minimal-mistakes@4.27.3
show_excerpts: true
minimal_mistakes_skin: dirt
title: norden.social
logo: https://media.norden.social/accounts/avatars/000/008/749/original/3d84c5056d5ef37c.png
locale: de-DE
email: moin@norden.social
description: Finanzielles, Statusupdates und andere Informationen rund um norden.social
github_username: norden-social
repository: norden-social/website
url: https://blog.norden.social
baseurl: ''
author:
  name: norden.social
  email: moin@norden.social
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    show_date: true
    read_time: false
    comments: false
    share: false
    related: false
    toc: false
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
    toc: false
social:
  type: Organisation
  name: norden.social e.V.
  links:
  - https://blog.norden.social
  - https://norden.social
  - https://norden.social/@leuchtturm
  - https://github.com/norden-social
footer:
  links:
  - label: Mastodon
    icon: fa-brands fa-mastodon
    url: https://norden.social/@leuchtturm
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/norden-social
og_image: https://media.norden.social/site_uploads/files/000/000/007/@1x/55cdf7c2197caa4e.png
compress_html:
  clippings: all
  ignore:
    envs: development
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-octicons
- jekyll-include-cache
safe: false
sass:
  sass_dir: assets/css
  style: compressed
include:
- _pages
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ".devcontainer/"
- ".github/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: '1,2,3'
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
paginate: 10
paginate_path: "/page/:num/"
collections:
  posts:
    output: true
    permalink: "/:categories/:title/"
  pages:
    output: true
    permalink: "/:title/"
feed:
  path: atom.xml
  limit: 20
seo:
  title: norden.social - Mastodon Instanz
  description: Finanzielles, Statusupdates und andere Informationen rund um norden.social
  author: norden.social e.V.
  image: https://media.norden.social/site_uploads/files/000/000/007/@1x/55cdf7c2197caa4e.png
  image_alt: norden.social Logo
  locale: de_DE
  type: website
